const Q_TO_FILE: Record<string, string> = {
  "caucasus mountains nature landscape": "caucasus-mountains-nature-landscape.jpg",
  "tea plantation china": "tea-plantation-china.jpg",
  "shizuoka green tea field japan": "shizuoka-green-tea-field-japan.jpg",
  "taiwan tea plantation alishan": "taiwan-tea-plantation-alishan.jpg",
  "kenya tea plantation field": "kenya-tea-plantation-field.jpg",
  "darjeeling tea plantation india": "darjeeling-tea-plantation-india.jpg",
  "provence herb field france landscape": "provence-herb-field-france-landscape.jpg",
  "alishan taiwan mountain tea plantation mist": "alishan-taiwan-mountain-tea-plantation-mist.jpg",
  "fujian china tea garden hills": "fujian-china-tea-garden-hills.jpg",
  "altai siberia pine forest wild nature": "altai-siberia-pine-forest-wild-nature.jpg",
  "altai wildflower meadow blooming summer": "altai-wildflower-meadow-blooming-summer.jpg",
  "rooibos bush south africa landscape": "rooibos-bush-south-africa-landscape.jpg",
  "provence lavender rows sunset purple": "provence-lavender-rows-sunset-purple.jpg",
  "oolong tea dry leaves twisted closeup": "oolong-tea-dry-leaves-twisted-closeup.jpg",
  "tea brewing process cup pouring": "tea-brewing-process-cup-pouring.jpg",
  "taiwan mountain landscape green hills": "taiwan-mountain-landscape-green-hills.jpg",
  "tieguanyin oolong tea leaf closeup": "oolong-tea-dry-leaves-twisted-closeup.jpg",
  "ceramic teapot tea ceremony pouring": "ceramic-teapot-tea-ceremony-pouring.jpg",
  "fujian terraced tea fields fog": "fujian-terraced-tea-fields-fog.jpg",
  "dried medicinal herbs bundle closeup": "dried-medicinal-herbs-bundle-closeup.jpg",
  "lingonberry berries leaves forest floor": "lingonberry-berries-leaves-forest-floor.jpg",
  "herbal tea brewing glass cup": "herbal-tea-brewing-glass-cup.jpg",
  "dried pressed flowers botanical specimen": "dried-pressed-flowers-botanical-specimen.jpg",
  "chamomile cornflower wild herbs bundle": "chamomile-cornflower-wild-herbs-bundle.jpg",
  "glass teapot floral brew sunlight": "glass-teapot-floral-brew-sunlight.jpg",
  "chamomile flowers field white petals": "chamomile-flowers-field-white-petals.jpg",
  "rooibos tea dried leaves wooden bowl": "rooibos-tea-dried-leaves-wooden-bowl.jpg",
  "evening tea cup candle cozy": "evening-tea-cup-candle-cozy.jpg",
  "dried lavender bundle rustic wooden table": "dried-lavender-bundle-rustic-wooden-table.jpg",
  "lemon balm melissa herb leaves green": "lemon-balm-melissa-herb-leaves-green.jpg",
  "lavender tea cup steam morning": "lavender-tea-cup-steam-morning.jpg",
  "green tea processing china": "green-tea-processing-china.jpg",
  "white tea buds withering": "white-tea-buds-withering.jpg",
  "yellow tea china": "yellow-tea-china.jpg",
  "oolong tea rolling processing": "oolong-tea-rolling-processing.jpg",
  "black tea processing fermentation": "black-tea-processing-fermentation.jpg",
  "puerh tea fermentation pile": "puerh-tea-fermentation-pile.jpg",
};

export function getLocalImage(query: string): string | null {
  const file = Q_TO_FILE[query];
  return file ? `/images/${file}` : null;
}
